# Generated by Django 5.1.3 on 2025-02-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0007_delete_worker_allocation_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip',
        ),
    ]
