# Generated by Django 5.1.3 on 2025-02-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0009_customer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='proof',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='zip',
        ),
        migrations.AddField(
            model_name='contractor',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
