# Generated by Django 5.1.3 on 2025-02-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0010_remove_contractor_address_remove_contractor_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('product_image', models.ImageField(null=True, upload_to='products/')),
            ],
        ),
    ]
