# Generated by Django 5.1.3 on 2025-02-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0011_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
