# Generated by Django 5.1.3 on 2025-02-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0013_booking_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
