# Generated by Django 5.1.3 on 2025-02-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0014_remove_cart_booking_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now=True)),
                ('booking_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buidingFaciliSysApp.customer')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buidingFaciliSysApp.booking'),
        ),
    ]
