# Generated by Django 5.1.3 on 2025-02-08 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0016_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry', models.TextField()),
                ('enquiry_date', models.DateTimeField(auto_now=True)),
                ('reply', models.TextField(null=True)),
                ('reply_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buidingFaciliSysApp.customer')),
            ],
        ),
    ]
