# Generated by Django 5.1.3 on 2025-02-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0017_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquiry',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='reply',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='fromuser',
            field=models.BooleanField(null=True),
        ),
    ]
